modLoader = "javafml" #mandatory
loaderVersion = "*" #mandatory. Allow all forge versions as we are definding what Minecraft versions we requre later on
license = "${license}" # Review your options at https://choosealicense.com/.
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
#clientSideOnly=true #optional

[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${version}" #mandatory
displayName = "${mod_name}" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional (see https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/)
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional (displayed in the mod UI)
logoFile = "assets/${mod_id}/icon.png" #optional
credits = "${credits}" #optional
authors = $mod_authors #optional
description = "${description}" #mandatory

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${compatible_forgemc_versions}"
ordering = "NONE"
side = "BOTH"